# theme.toml
name = "Furniture"
license = "MIT"
licenselink = "https://github.com/lowply/furniture/blob/master/LICENSE.md"
description = "Furniture - A hugo theme for fixture.jp"
homepage = "https://github.com/lowply/furniture/"
tags = ["blog"]
min_version = 1.0

[author]
  name = "lowply"
  homepage = "https://github.com/lowply"
